tax-main-frontend-backup
/
8052c8d
Jul 18, 2025, 2:58 PM
Active


Details
Build Logs
Deploy Logs

Filter
Filter logs using "", (), AND, OR, -



You reached the start of the range → Jul 18, 2025, 2:58 PM

Starting Container

npm warn config production Use `--omit=dev` instead.

 

> taxbox-ai-frontend@1.0.0 start

> react-scripts start

 

(node:22) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.

(Use `node --trace-deprecation ...` to show where the warning was created)

(node:22) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.

Starting the development server...

 
